FROM ruby:4-alpine AS builder

RUN apk add --no-cache build-base gcompat git

WORKDIR /usr/src/app
COPY Gemfile Gemfile.lock ./
RUN bundle config --global frozen 1 && \
    bundle install && \
    bundle clean --force && \
    rm -rf ~/.bundle/cache /usr/local/bundle/cache

FROM ruby:4-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/local/bundle /usr/local/bundle

COPY Gemfile Gemfile.lock ./

COPY app app
COPY views views
COPY server.rb server.rb
COPY public public

EXPOSE 5678
CMD ["bundle", "exec", "ruby", "server.rb", "-e", "development", "-p", "5678", "-o", "0.0.0.0"]
