source "https://gem.coop"

gem "json"
gem "sinatra"
gem "csv"
gem "sqlite3"
gem "fuzzy_match"
gem "sanitize"
gem "rackup"
gem "puma"
gem "rack-cache"
gem "sinatra-contrib"
gem "rerun"
gem "redis"
gem "erubi"
gem "redcarpet"
gem "sinatra-static-assets", "~> 1.0"
