when:
  branch: main
  event: [push, pull_request]

variables:
  - &file Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/theriodex

steps:
  dryrun:
    image: woodpeckerci/plugin-kaniko
    settings:
      dockerfile: *file
      platforms: linux/amd64
      dry_run: true
      repo: *repo
      tags: latest

  publish:
    image: woodpeckerci/plugin-kaniko
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      registry: codeberg.org
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
