when:
  branch: main
  event: [push, pull_request]

variables:
  - &file Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/theriodex

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx:6
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      tags: latest

  publish_to_codeberg:
    image: woodpeckerci/plugin-docker-buildx:6
    settings:
      registry: codeberg.org
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      tags: latest
      username: ${CI_REPO_OWNER}
      password: ${{ secrets.cb_token }}

  deploy:
    image: debian
    environment:
      SCW_SECRET_KEY:
        from_secret: scw_key
      CONTAINER_REGION:
        from_secret: container_region
      CONTAINER_ID:
        from_secret: container_id
    commands:
      - |
        curl -X POST -H "X-Auth-Token: ${{ secrets.scw_key }}" -H "Content-Type: application/json" -d '{}' "https://api.scaleway.com/containers/v1beta1/regions/${{ secrets.container_region }}/containers/${{ secrets.container_id }}/deploy"
