when:
  branch: main
  event: [push, pull_request]

variables:
  - &file Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/theriodex

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx:6
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      tags: latest

  publish_to_codeberg:
    image: woodpeckerci/plugin-docker-buildx:6
    settings:
      registry: codeberg.org
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      tags: latest
      username: ${CI_REPO_OWNER}
      password: ${{ secrets.cb_token }}

  deploy:
    image: debian
    env: 
      SCW_SECRET_KEY: ${{ secrets.scw_key }}
      CONTAINER_ID: ${{ secrets.container_id }}
      container_region: ${{ secrets.container_region }}
    commands:
      - |
        curl -X POST -H "X-Auth-Token: $SCW_SECRET_KEY" -H "Content-Type: application/json" -d '{}' "https://api.scaleway.com/containers/v1beta1/regions/$CONTAINER_REGION/containers/$CONTAINER_ID/deploy"
