when:
  branch: main
  event: [push, pull_request]

variables:
  - &file Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/theriodex

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx:6
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      tags: latest

  publish_to_codeberg:
    image: woodpeckerci/plugin-docker-buildx:6
    settings:
      registry: codeberg.org
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      tags: latest
      username: ${CI_REPO_OWNER}
      password: ${{ secrets.CB_TOKEN }}