when:
  branch: main
  event: [push, pull_request]

variables:
  - &file Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/theriodex

steps:
  lint:
    image: ruby:3.2.9-trixie
    commands:
      - gem install rubocop rubocop-performance rubocop-rails rubocop-minitest
      - rubocop -A

  build_and_publish_to_codeberg:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      registry: codeberg.org
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
